name: plaid-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
##### RUN #####
#---# base
  - tqdm
#---# io
  - pyyaml
#---# storage backends
  - pycgns-core
  - zarr
  - webdataset
#---# SciML
  - scikit-learn
  - datasets
  - numpy
  - matplotlib-base
#---# data validation
  - pydantic
##### DEV/TESTS/EXAMPLES #####
#---# mesh/graph libs
  - muscat-core=2.5.1
#---# base
  - rich
#---# optim
  - optuna
#---# testing
  - pytest
  - pytest-cov
#---# code formatters
  - ruff
#---# dev
  - pre-commit
#---# doc
  - sphinx
  - sphinx-autoapi
  - sphinx-tabs
  - sphinxcontrib-bibtex
  - myst-nb
  - myst-parser
  - furo
  - jupytext
